---
title: '2018-12-26'
author: "江宗樺"
date: "12/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr); library(dplyr); library(stringr); library(lubridate)
```

```{r}
install.packages("plotly")
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1L,3L,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

#sol1
```{r}
plasticContainer["greenBox"] # or plasticContainer[c(1,2)]
```

#sol2
```{r}
plasticContainer[["greenBox"]] # or plasticContainer[[1]]
```

#sol3
```{r}
plasticContainer$greenBox
# [[]] = $ 兩個中括號等於錢符號的功能 
```

#承上，從GreenBox中取出paper
#sol1
```{r}
plasticContainer["greenBox"]$greenBox[1]
```

#sol2
```{r}
plasticContainer[["greenBox"]][1]
```

#sol3
```{r}
plasticContainer$greenBox[1]
```

## plotly example

```{r}
download.file("https://github.com/tpemartin/github-data/blob/master/plotly_4070_neda.Rda?raw=true",destfile = "plotly_4070_neda.Rda")
load("plotly_4070_neda.Rda")
library(plotly)
plotly_4070_neda
```

```{r}
plotly_4070_neda$x$layout$shapes[[1]]$opacity <- 0.7
```

```{r}
plotly_4070_neda
```

## 迴圈

```{r}
library(readr)
transcriptData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcript100_102.csv",
                  col_types = cols(
                    學期成績="n"
                  ))
totalCredits<-function(x){
  transcriptData[transcriptData$學號==x,]->subsample 
  subsample %>%
    mutate(
      及格=(學期成績>=60)
    ) %>%
    summarise(
      學號=學號[1],
      總修習學分數=sum(學分數),
      總實得學分數=sum(學分數[及格])
    )  
}
```

```{r}
transcriptData -> subsample
subsample$學號 %>% unique -> 符合條件學號
```

```{r}
seq_along(符合條件學號)
```

```{r}
# 0
creditResults<-vector("list",length(符合條件學號))
i<-1
# 1
符合條件學號[i]
# 2
totalCredits(符合條件學號[i])
# 3
creditResults[[i]]<-totalCredits(符合條件學號[i])
```

```{r}
for(i in seq_along(符合條件學號)){
  creditResults[[i]] <- totalCredits(符合條件學號[i])
}
```

i<-200
```{r}
creditResults[[200]]
```


## nested data frame

```{r}
library(readr)
library(tidyr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/libraryData2.csv")
```

```{r}
library(dplyr)
libraryData %>% 
  filter(學院=="人文學院")
```

```{r}
libraryData %>%
  group_by(學院) %>%
  nest-> nestLibraryData
nestLibraryData %>%
  filter(學院=="人文學院") %>%
  .$data
```


```{r}
libraryData %>%
  group_by(學院) %>%
  nest(.key="各院借閱資料") ->
  libraryDataNested
```

```{r}
libraryDataNested
```




