
```{r}
library(googlesheets)
```

```{r}
gs_auth(new_user = TRUE)
```

```{r}
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")
classSurvey<-gs_read(gsSurvey,ws=1)
```


```{r}
(classSurvey$性別 == "男")

(classSurvey$本學期學分數 > 20)

(classSurvey$性別 == "男" | 
    classSurvey$本學期學分數 > 20)
```

```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
StuDF$StuID
StuDF[,c("StuID")]
StuDF$name
StuDF[,c("name")]
```

```{r}
names(gsSurvey)
```

```{r}
gsSurvey$links$type
```

```{r}
names(StuDF)
```

```{r}
names(StuDF) <- c("學號","姓名","成績")
names(StuDF)
```

```{r}
names(StuDF)[2] <- c("姓名") #中括號內為第幾個字
names(StuDF)
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
levels(student$身高級距) <- c("小個子","小個子","小個子","小個子","小個子","中等個子","中等個子","大個子","大個子")
levels(student$身高級距) 
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
levels(student$身高級距)[c(1:3)] <- c("(0:160)")
levels(student$身高級距)
```

## 課堂練習

```{r}
library(googlesheets)
#gs_auth(new_user = TRUE)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```

1.1
```{r}
dim(classSurvey)
nrow(classSurvey)
ncol(classSurvey)
```

1.2
```{r}
class(classSurvey$學號)
# 學號轉成character
classSurvey$學號 <- as.character(classSurvey$學號)
# 學號取出字串第2-4位 存成 年級
library(stringr)
classSurvey$年級 <- str_sub(classSurvey$學號,2,4)
# 年級 轉 factor
classSurvey$年級 <- as.factor(classSurvey$年級)
# 年級進行 generic replacement
levels(classSurvey$年級) <- c("大四以上","大三","大二","大一")
levels(classSurvey$年級)
classSurvey$年級
```

1.3
```{r}

```

1.4
```{r}

```

1.5
```{r}

```

大一課外活動的統計
1.6
```{r}
#篩出大一的樣本
freshIndi
#針對小樣本的課外活動去統計
library(stringr)
a <- str_split_fixed(freshActivity,","n=5)
b <- str_c(a) 
table(b)
length(freshActivity)
```





