
```{r}
library(readr)
libraryData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/library100_102.csv")
```

```{r}
library(readr); library(dplyr); library(stringr); library(lubridate)
```

```{r}
#sol(1)
libraryData$書籍館藏地 <- as.factor(libraryData$書籍館藏地)
levels(libraryData$書籍館藏地) -> storageLocations
```

```{r}
 #sol(2)
libraryData$書籍館藏地 %>% 
  as.factor %>% 
  levels -> storageLocations
```

```{r}
i<-1
# 1
storageLocation_i <- storageLocations[i] 
# 2
numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
subsample_i <- libraryData[numericalIndexForSubsample,]
# 3
borrowCount_i <- nrow(subsample_i)
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
i<-1
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i
```

```{r}
# 0
allBorrowCount <- vector("numeric",18)
for(i in c(1:18)){
  # 1
  storageLocation_i <- storageLocations[i] 
  # 2
  numericalIndexForSubsample<-which(libraryData$書籍館藏地==storageLocation_i)
  subsample_i <- libraryData[numericalIndexForSubsample,]
  # 3
  borrowCount_i <- nrow(subsample_i)
  # 4
  allBorrowCount[[i]]<-borrowCount_i  
}
```

```{r}
names(allBorrowCount) <- storageLocations 
```

#每一個學院的借書量
```{r}

libraryData$學院 %>%
  as.factor %>%
  levels -> college
```

```{r}
allBorrowCount2 <- vector("numeric",6)
for(i in c(1:6)){
  # 1
  college_i <- college[i] 
  # 2
  numericalIndexForSubsample2<-which(libraryData$學院==college_i)
  subsample2_i <- libraryData[numericalIndexForSubsample2,]
  # 3
  borrowCount2_i <- nrow(subsample2_i)
  # 4
  allBorrowCount2[[i]]<-borrowCount2_i  
}
names(allBorrowCount2) <- college
allBorrowCount2
```

## 不同學院借書量
```{r}
libraryData$學院 %>% as.factor %>% levels -> college
```

#每位學生借書量
```{r}
libraryData$學號 %>% as.factor %>% levels -> student
libraryData$學號 %>% unique -> student
#0
studentBorrow <- vector("numeric", length(student))
for(i in c(1:length(student))){
# 1
student_i <- student[i]
# 2
numericalIndex <- which(libraryData$學號 == student_i)
studentSubsample_i <- libraryData[numericalIndex,]
# 3
studentBorrow_i <- nrow(studentSubsample_i)
# 4
studentBorrow[[i]] <- studentBorrow_i
}
```

$$\sum_{i=1}^{10} i$$

```{r}
ans<-0
for(i in 1:10){
  newlyAdded<-i
  ans<-ans+newlyAdded
}
```

```{r}
libraryData %>%
  group_by(書籍館藏地) %>%
  summarise(
    borrowCount=length(學號)
  ) -> result
result
```

#double loops
```{r}
libraryData %>%
  mutate(
    學系=str_sub(學號,5,6)
    ## 相當於 libraryData$學系 <- str_sub(libraryData$學號,5,6)
  ) -> libraryData
```

```{r}
libraryData %>%
  group_by(學院,入學年) %>%
  summarise(
    borrowCount=length(學號)
  ) -> result2
result2
```
 
 
```{r}
#0 container
 for(i in seq_along(College)){
  for(j in seq_along(EntranceYear)){
    #1
    
    #2
    
    #3
    
    #4
    
    
  }
  
  
}
 ```
